defaults:
  - base_config
  - _self_

run_id: 4He
nparticles: 4
save_path: output/${hamiltonian.form}/${nparticles}particles/${dimension}D/${optimizer.form}.${run_id}/
hamiltonian:
  spin:
    total_spin: ${nparticles}
    z_projection: 2
  isospin:
    total_spin: ${nparticles}
    z_projection: 2
