defaults:
  - hamiltonian: Nuclear
  - optimizer: Flat
  - wavefunction: DeepSets
iterations: 5
sampler:
  n_thermalize: 5000
  n_void_steps: 200
  n_observable_measurements: 20
  n_walkers_per_observation: 200
  n_concurrent_obs_per_rank: 20
nparticles: 2
dimension: 3
run_id: ???
save_path: output/${hamiltonian.form}/${nparticles}particles/${dimension}D/${optimizer.form}.${run_id}/
model_name: ${hamiltonian.form}_${nparticles}part_${dimension}D.model
